include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  exclude:
    #    - "**/test/**"
    - "**/_source/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "**/*.pb.dart"
    - "**/*.pbenum.dart"
    - "**/*.pbgrpc.dart"
    - "**/*.pbjson.dart"

linter:
  rules:
    lines_longer_than_80_chars: true
    sort_pub_dependencies: false
