name: Flutter

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: latest

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      # - name: Run tests
      #   run: flutter test
